In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
print(torch.__version__)

2.4.1+cpu


In [5]:
# Introduction to tensors
# creating tensors

In [6]:
# Scalar

In [7]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
# vector

In [9]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# matrix

In [13]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix.ndim

2

In [15]:
matrix[0]

tensor([7, 8])

In [16]:
matrix[1]

tensor([ 9, 10])

In [17]:
# tensor
tensor = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([1, 3, 3])

In [21]:
# Random Tensor

In [22]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0061, 0.6304, 0.5963, 0.1446],
        [0.3402, 0.2505, 0.8258, 0.8893],
        [0.4307, 0.6745, 0.1326, 0.7379]])

In [23]:
random_tensor

tensor([[0.0061, 0.6304, 0.5963, 0.1446],
        [0.3402, 0.2505, 0.8258, 0.8893],
        [0.4307, 0.6745, 0.1326, 0.7379]])

In [24]:
torch.rand(3,3)

tensor([[0.9355, 0.9951, 0.7593],
        [0.0379, 0.4153, 0.5428],
        [0.4450, 0.5722, 0.4696]])

In [25]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

In [28]:
ones.size

<function Tensor.size>

In [29]:
torch.range(0,10)

C:\Users\himanshu\AppData\Local\Temp\ipykernel_6132\497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
one_to_ten = torch.arange(start = 1,end = 11,step =1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
# mainpulating Tensor
# Addition
# subtraction
# Multiplication(element wise)
# dividation
# Matrix Multiplication

In [33]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [34]:
tensor*10

tensor([10, 20, 30])

In [35]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [36]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [37]:
# Matrix multiplication
# Inner dimensions must match:
# (3,2)@(3,2)--won't work
# (3,2)@(2,3) -- will work
# (2,3)@(3,2)--will work

In [38]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.5894, 0.8359, 0.8775],
        [0.5265, 0.7331, 0.7572],
        [0.6365, 0.8406, 0.8257]])

In [39]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.1282, 0.3864],
        [0.2448, 0.5615]])

In [40]:
# Tensor Aggregation(max,min,sum,mean etc)

In [41]:
# create Aggregate
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
# find the min
torch.min(x)

tensor(0)

In [43]:
x.min()

tensor(0)

In [44]:
x.max()

tensor(90)

In [45]:
# find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [46]:
x.type(torch.float32).mean()

tensor(45.)

In [47]:
# find the sum
torch.sum(x)

tensor(450)

In [48]:
x.sum()

tensor(450)

In [49]:
# finding the positional min & max
x.argmin()

tensor(0)

In [50]:
x.argmax()

tensor(9)

In [51]:
# Reshaping

In [52]:
# lets create a tensor
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [53]:
# add an extra Dimention
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
# view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [55]:
# changeing z changes x
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [56]:
x_stacked = torch.stack([x,x,x,x],dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [57]:
# torch.squeeze().remove all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [58]:
x_reshaped.shape

torch.Size([1, 9])

In [59]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [60]:
x_reshaped.squeeze().shape

torch.Size([9])